apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "simple-app.labels" . | nindent 4 }}
  name: {{ include "simple-app.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "simple-app.selectorLables" . | nindent 6 }}
  strategy: {}
  template:
    metadata:
      labels:
        {{- include "simple-app.selectorLables" . | nindent 8 }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag}}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        
status: {}
